environment:
  COVERALLS_REPO_TOKEN:
    secure: sxoCWFzAUW5WrH5KKKY38kZo1oB3Bu+WWJDshymilkDq/rKR4j9qXmrf6Ae/ekt8
  COVERALLS_PARALLEL: true
  CI: true
  matrix:
    - nodejs_version: '6'
    - nodejs_version: '5'
    - nodejs_version: '4'
    - nodejs_version: '0.12'
    - nodejs_version: '0.10'
install:
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
matrix:
  fast_finish: true
branches:
  only:
  - master
build: off
deploy: off
version: '{build}'
test_script:
  - npm test -- --reporter=tap
