environment:
  COVERALLS_REPO_TOKEN:
    secure: sxoCWFzAUW5WrH5KKKY38kZo1oB3Bu+WWJDshymilkDq/rKR4j9qXmrf6Ae/ekt8
  COVERALLS_PARALLEL: true
  CI: true
  matrix:
    - nodejs_version: '0.10'
    - nodejs_version: '0.12'
    - nodejs_version: '4'
    - nodejs_version: '5'
    - nodejs_version: '6'
install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm -g install npm
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
matrix:
  fast_finish: true
  allow_failures:
    - nodejs_version: '0.10'
branches:
  only:
  - master
build: off
deploy: off
version: '{build}'
test_script:
  - npm run test:tap || exit 0
  - npm run tap:xunit || exit 0
after_test:
  - ps: |
      $url = "https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)"
      $file = 'xunit-results.xml'
      $xml = Get-Content $file
      Set-Content $file '<?xml version="1.0" encoding="UTF-8"?>'
      Add-Content $file "`n"
      Add-Content $file $xml
      (New-Object 'System.Net.WebClient').UploadFile($url, (Resolve-Path $file))
artifacts:
  - path: tap-results.txt
  - path: xunit-results.xml
